server:
  port: 8080


eventTopic: eventTopic
useRest : false
---
spring:
  profiles: default
  kafka:
#    bootstrap-servers: http://35.200.47.242:31090
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

productUrl: http://localhost:8085

server:
  port: 8081
---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      enable-auto-commit: true

productUrl: http://product:8085